//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG_Part2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public Nullable<System.DateTime> DateSupplied { get; set; }
        public int FarmerId { get; set; }
    
        public virtual Farmer Farmer { get; set; }

        public virtual IEnumerable<Product> FilteredProducts { get; set; }

        public virtual IEnumerable<Farmer> FarmerList { get; set; }
    }
}
